"""WindowsInventory - IInventory implementation for Windows.

Spawns the inventory list script (``adapters/windows/scripts/inventory/list.ps1``),
parses the resulting ``ascendo/v1`` sidecar, and converts ``items[]`` back into
:class:`Package` instances.

The inventory is invoked OUTSIDE the orchestrator's 5-phase pipeline. Each
call generates its own ``uuid4`` run-id and uses a private temporary
directory for the sidecar; this is intentional because:

* The dashboard's "what's installed" view, plugin context, and ad-hoc
  scripts may want a fresh inventory snapshot at any time, independent of
  any in-flight maintenance run.
* The ``check__winget.json`` sidecar filename collides with the
  WingetManager check-phase emission. By using distinct run directories
  (different uuid4 in different tempdirs) the two never overwrite each
  other. An INFO-level sentinel message in the sidecar
  ('Generated by inventory/list.ps1, not a phase pipeline.') lets
  consumers tell the two apart even when archived side-by-side.

The Python <-> PowerShell IPC contract mirrors :class:`WingetManager`:
the script writes its sidecar to ``<OutputDir>/<RunId>/check__winget.json``
and exits. Python re-reads via :func:`read_sidecar`. Crashes that produce
no sidecar surface as :class:`ManagerError`.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Iterable
from datetime import datetime, timezone
from pathlib import Path
from typing import ClassVar
from uuid import uuid4

from ascendo.interfaces.inventory import IInventory
from ascendo.utils.proc import no_window_kwargs

# ManagerError reused for parity with WingetManager: a dropped IPC contract
# (script crash, missing sidecar, parse failure) is the same conceptual
# error class regardless of whether the failing script is a phase manager
# or an inventory enumerator. Reusing the type avoids forcing callers to
# handle two structurally-identical exceptions.
from ascendo.interfaces.package_manager import ManagerError
from ascendo.models.host import HostInfo, OperatingSystem
from ascendo.models.package import Package, SourceType
from ascendo.models.result import Item, ItemStatus, MessageLevel, Message, Summary
from ascendo.models.run import Phase, PhaseStatus, RunInfo, Trigger
from ascendo.models.sidecar import Sidecar, SidecarSchema, ToolInfo
from ascendo.orchestrator.sidecar_io import (
    SidecarIOError,
    SidecarReadError,
    read_sidecar,
)

_log = logging.getLogger(__name__)


class WindowsInventory(IInventory):
    """Lists installed packages on Windows by shelling out to ``inventory/list.ps1``.

    Args:
        scripts_dir: Path to ``adapters/windows/scripts/`` (set by the
            adapter; the script we run lives at
            ``<scripts_dir>/inventory/list.ps1``).
        lib_dir: Path to ``adapters/windows/lib/`` (informational; the
            script imports the .psm1 files relatively).
        pwsh_path: Optional override for the PowerShell executable. When
            ``None``, resolves at run time (``pwsh.exe`` then
            ``powershell.exe``).
        timeout_sec: Per-call timeout. Default ``300`` (5 min). Inventory
            is read-only and should complete much faster than a phase.
    """

    SCRIPT_REL: ClassVar[str] = "inventory/list.ps1"
    DEFAULT_TIMEOUT_SEC: ClassVar[int] = 300

    def __init__(
        self,
        *,
        scripts_dir: Path,
        lib_dir: Path,
        pwsh_path: str | None = None,
        timeout_sec: int = DEFAULT_TIMEOUT_SEC,
    ) -> None:
        self._scripts_dir: Path = Path(scripts_dir)
        self._lib_dir: Path = Path(lib_dir)
        self._pwsh_override: str | None = pwsh_path
        self._pwsh_resolved: str | None = None
        self._timeout_sec: int = timeout_sec

    # ── IInventory ───────────────────────────────────────────────────

    def list_installed(
        self,
        host: HostInfo,
        *,
        categories: Iterable[str] | None = None,
    ) -> list[Package]:
        """Spawn ``list.ps1``, parse the emitted sidecar, return a list of
        :class:`Package`.

        On non-Windows hosts or hosts where neither ``winget`` nor
        ``winget.exe`` is on PATH, returns an empty list (no error). This
        matches the IInventory contract: a missing source is not an
        error condition, just zero items.

        Args:
            host: Host context. Linux / macOS hosts return ``[]``.
            categories: Optional iterable of :class:`SourceType` values
                (or their string equivalents) used to filter the result.
                When set, only packages whose ``category`` is in this
                set are returned. ``None`` means no filter (default).

        Returns:
            List of :class:`Package`. Order matches the sidecar's
            ``items[]`` order; callers needing stable ordering MUST sort.

        Raises:
            ManagerError: pwsh unavailable when winget IS on PATH, script
                crashed without emitting a sidecar, sidecar missing on
                clean exit, or sidecar parse failure.
        """
        # Source-availability gate. The IInventory contract says inventory
        # consolidates per-source listings; on a host without winget there
        # are simply zero winget packages to enumerate -> empty list, no
        # error.
        if host.os is not OperatingSystem.WINDOWS:
            return []
        if not (shutil.which("winget") or shutil.which("winget.exe")):
            return []

        script_path = self._scripts_dir / self.SCRIPT_REL
        pwsh = self._resolve_pwsh()

        # Each list_installed call is its own snapshot — fresh uuid4,
        # private tempdir. This keeps inventory-emitted sidecars from
        # ever colliding with WingetManager phase=check sidecars: even
        # though both write `check__winget.json`, they live under
        # different (run-id, base-dir) tuples.
        invocation_run_id = uuid4()

        with tempfile.TemporaryDirectory(prefix="ascendo-inventory-") as tmp_str:
            output_dir = Path(tmp_str)

            argv = self._build_argv(
                pwsh=pwsh,
                script_path=script_path,
                run_id=invocation_run_id,
                output_dir=output_dir,
            )

            _log.debug(
                "WindowsInventory.list_installed: run_id=%s argv=%r",
                invocation_run_id,
                argv,
            )

            try:
                completed = subprocess.run(  # noqa: S603 (argv list, not shell)
                    argv,
                    capture_output=True,
                    text=True,
                    timeout=self._timeout_sec,
                    check=False,
                    **no_window_kwargs(),
                )
            except subprocess.TimeoutExpired as exc:
                msg = (
                    f"inventory list script timed out after "
                    f"{self._timeout_sec}s: {script_path}"
                )
                raise ManagerError(msg) from exc
            except OSError as exc:
                msg = f"failed to spawn pwsh for inventory list: {exc}"
                raise ManagerError(msg) from exc

            sidecar_path = (
                output_dir
                / str(invocation_run_id)
                / "check__winget.json"
            )

            if not sidecar_path.exists():
                msg = self._format_missing_sidecar_error(
                    script_path=script_path,
                    sidecar_path=sidecar_path,
                    completed=completed,
                )
                raise ManagerError(msg)

            try:
                sidecar = read_sidecar(sidecar_path)
            except (SidecarReadError, SidecarIOError) as exc:
                msg = (
                    f"inventory list script wrote unparseable sidecar "
                    f"at {sidecar_path}: {exc}"
                )
                raise ManagerError(msg) from exc

            if completed.returncode != 0:
                _log.warning(
                    "inventory list script exited %d but produced a valid "
                    "sidecar; trusting the sidecar (status=%s)",
                    completed.returncode,
                    sidecar.status.value,
                )

            return self._sidecar_to_packages(sidecar, categories=categories)

    def emit_sidecar(
        self,
        run: RunInfo,
        host: HostInfo,
        packages: list[Package],
    ) -> Sidecar:
        """Synthesise an inventory sidecar from a pre-built list of
        :class:`Package`.

        Used when the orchestrator wants to persist an inventory inside a
        bigger run (e.g. as part of a scheduled snapshot) rather than have
        the script run itself. The returned :class:`Sidecar` has
        ``phase=check``, ``category=winget``, and one ``items[]`` entry
        per package with ``status='success'`` (the package is installed).

        Args:
            run: The orchestrator's :class:`RunInfo`. Its ``id`` becomes
                the sidecar's run id (in contrast to ``list_installed``,
                which generates a fresh uuid4 per call).
            host: Host context for the ``host`` block of the sidecar.
            packages: Pre-enumerated list of :class:`Package`.

        Returns:
            A validated :class:`Sidecar` (pydantic round-trip enforced).
        """
        now = datetime.now(timezone.utc)

        items: list[Item] = []
        for pkg in packages:
            items.append(
                Item(
                    id=pkg.id,
                    name=pkg.name,
                    category=pkg.category,
                    source={"type": pkg.category, "feed": None, "url": None},
                    status=ItemStatus.SUCCESS,
                )
            )

        summary = Summary(
            total=len(items),
            success=len(items),
            up_to_date=0,
            failed=0,
            skipped=0,
            planned=0,
            partial=0,
            duration_ms=None,
            exit_code=0,
        )

        tool = ToolInfo(name="winget", version="unknown", binary_path=None)

        return Sidecar.model_validate(
            {
                "schema": SidecarSchema.V1_ASCENDO,
                "run": run,
                "host": host,
                "tool": tool,
                "phase": Phase.CHECK,
                "category": SourceType.WINGET,
                "started_at": now,
                "finished_at": now,
                "status": PhaseStatus.SUCCESS,
                "items": items,
                "summary": summary,
                "messages": [
                    Message(
                        level=MessageLevel.INFO,
                        text=(
                            "Generated by WindowsInventory.emit_sidecar "
                            "(in-memory, not a phase pipeline)."
                        ),
                    ),
                ],
            }
        )

    # ── Internals ────────────────────────────────────────────────────

    def _build_argv(
        self,
        *,
        pwsh: str,
        script_path: Path,
        run_id: object,
        output_dir: Path,
    ) -> list[str]:
        """Build the pwsh argv for ``inventory/list.ps1``.

        Mirrors :meth:`WingetManager._build_argv` so the same conventions
        apply (``[switch] $DryRun``, single-token argv values, etc.).
        Inventory is read-only, so we do NOT emit ``-DryRun``: dry-run is
        meaningless for a non-mutating call.
        """
        return [
            pwsh,
            "-NoProfile",
            "-NonInteractive",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            str(script_path),
            "-RunId",
            str(run_id),
            "-Trigger",
            Trigger.PLUGIN.value,
            "-Profile",
            "inventory",
            "-OutputDir",
            str(output_dir),
        ]

    def _sidecar_to_packages(
        self,
        sidecar: Sidecar,
        *,
        categories: Iterable[str] | None,
    ) -> list[Package]:
        """Convert a sidecar's ``items[]`` into :class:`Package` instances.

        Items with synthetic IDs (``__phase_error__`` etc.) are silently
        dropped — they are diagnostic markers, not packages.
        """
        # Normalise the categories filter into a set of SourceType values
        # so we can compare against item.category cleanly. Accept either
        # SourceType members or their string equivalents.
        cat_filter: set[SourceType] | None = None
        if categories is not None:
            cat_filter = set()
            for cat in categories:
                if isinstance(cat, SourceType):
                    cat_filter.add(cat)
                else:
                    try:
                        cat_filter.add(SourceType(cat))
                    except ValueError:
                        # Unknown category strings are silently ignored;
                        # callers passing typos shouldn't crash.
                        _log.warning(
                            "WindowsInventory: ignoring unknown category %r",
                            cat,
                        )

        packages: list[Package] = []
        for item in sidecar.items:
            if item.id.startswith("__") and item.id.endswith("__"):
                # Diagnostic synthetic items emitted by the script's catch
                # block (e.g. __phase_error__).
                continue
            if cat_filter is not None and item.category not in cat_filter:
                continue
            packages.append(
                Package(id=item.id, name=item.name, category=item.category)
            )
        return packages

    def _format_missing_sidecar_error(
        self,
        *,
        script_path: Path,
        sidecar_path: Path,
        completed: subprocess.CompletedProcess[str],
    ) -> str:
        """Compose a debugging-friendly error for the missing-sidecar case."""

        def _tail(s: str | None, limit: int = 800) -> str:
            if not s:
                return "<empty>"
            if len(s) <= limit:
                return s
            return f"...<truncated {len(s) - limit} chars>...{s[-limit:]}"

        return (
            f"inventory list script produced no sidecar.\n"
            f"  script:        {script_path}\n"
            f"  expected at:   {sidecar_path}\n"
            f"  exit code:     {completed.returncode}\n"
            f"  stderr (tail): {_tail(completed.stderr)}\n"
            f"  stdout (tail): {_tail(completed.stdout)}"
        )

    def _resolve_pwsh(self) -> str:
        """Find ``pwsh.exe`` (preferred) or ``powershell.exe``. Cache result.

        Mirrors :meth:`WingetManager._resolve_pwsh` exactly so the two
        managers stay consistent on heterogeneous hosts.
        """
        if self._pwsh_resolved is not None:
            return self._pwsh_resolved

        if self._pwsh_override is not None:
            self._pwsh_resolved = self._pwsh_override
            return self._pwsh_resolved

        for candidate in ("pwsh.exe", "pwsh", "powershell.exe", "powershell"):
            found = shutil.which(candidate)
            if found is not None:
                self._pwsh_resolved = found
                return found

        msg = (
            "no PowerShell binary on PATH (looked for pwsh.exe, pwsh, "
            "powershell.exe, powershell). Install PowerShell 7+ or pass "
            "pwsh_path= explicitly."
        )
        raise ManagerError(msg)
