"""Self-contained Markdown report for a single run.

Renders run summary + per-phase counts + diagnostics + advisories from the
JSON sidecars under ``logs/runs/<id>/``.  Used by ``GET /runs/{id}/report.md``
to give the operator a copy-paste-ready artefact for ticket attachments,
audit reviews, or sharing in chat.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _read(p: Path) -> dict | None:
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None


def render(run_dir: Path) -> str:
    run_json = run_dir / "run.json"
    summary = _read(run_json) or {}
    lines: list[str] = []

    lines.append(f"# Update run report — `{summary.get('run_id', run_dir.name)}`")
    lines.append("")
    lines.append(f"- Status: **{summary.get('status', '?')}**")
    if summary.get("ended_at"):
        lines.append(f"- Ended: `{summary['ended_at']}`")
    if summary.get("needs_reboot"):
        lines.append("- ⚠ Reboot required")
    lines.append("")
    lines.append("## Phases")
    lines.append("")
    lines.append("| Category | Phase | Exit | OK | Warn | Err | Reboot |")
    lines.append("|----------|-------|------|----|------|-----|--------|")

    sidecars = sorted(run_dir.glob("*/*.json"))
    for path in sidecars:
        if path.name == "run.json":
            continue
        d = _read(path) or {}
        s = d.get("summary") or {}
        lines.append(
            "| {} | {} | {} | {} | {} | {} | {} |".format(
                d.get("category", "?"),
                d.get("kind", "?"),
                d.get("exit_code", "?"),
                s.get("ok", 0),
                s.get("warn", 0),
                s.get("err", 0),
                "yes" if d.get("needs_reboot") else "no",
            )
        )

    lines.append("")
    lines.append("## Diagnostics")
    lines.append("")
    any_diag = False
    for path in sidecars:
        if path.name == "run.json":
            continue
        d = _read(path) or {}
        diags = d.get("diagnostics") or []
        if not diags:
            continue
        any_diag = True
        lines.append(f"### {d.get('category', '?')}:{d.get('kind', '?')}")
        lines.append("")
        for diag in diags:
            level = diag.get("level", "info")
            code  = diag.get("code", "?")
            msg   = diag.get("msg", "")
            lines.append(f"- **{level.upper()}** `{code}` — {msg}")
        lines.append("")

    if not any_diag:
        lines.append("_No diagnostics recorded._")
        lines.append("")

    lines.append("## Advisories")
    lines.append("")
    advisories: list[str] = []
    for path in sidecars:
        if path.name == "run.json":
            continue
        d = _read(path) or {}
        for a in d.get("advisory") or []:
            advisories.append(f"- ({d.get('category', '?')}) {a}")
    if advisories:
        lines.extend(advisories)
    else:
        lines.append("_No advisories._")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_Generated by Ascendo dashboard._")
    return "\n".join(lines) + "\n"


def render_run_id(run_id: str, runs_dir: Path) -> str | None:
    run_dir = runs_dir / run_id
    if not run_dir.exists():
        return None
    return render(run_dir)
