"""MacOSInventory - IInventory implementation for macOS.

Spawns the inventory list script (``adapters/macos/scripts/inventory/list.sh``),
parses the resulting ``ascendo/v1`` sidecar, and converts ``items[]`` back into
:class:`Package` instances.

The inventory is invoked OUTSIDE the orchestrator's 5-phase pipeline. Each
call generates its own ``uuid4`` run-id and uses a private temporary
directory for the sidecar; this is intentional because:

* The dashboard's "what's installed" view, plugin context, and ad-hoc
  scripts may want a fresh inventory snapshot at any time, independent of
  any in-flight maintenance run.
* The ``check__inventory.json`` sidecar filename is distinct from per-source
  phase emissions. By using distinct run directories (different uuid4 in
  different tempdirs) the two never overwrite each other. An INFO-level
  sentinel message in the sidecar ('Generated by inventory/list.sh, not a
  phase pipeline.') lets consumers tell the two apart even when archived
  side-by-side.

The Python <-> Bash IPC contract mirrors :class:`BrewManager`:
the script writes its sidecar to ``<OutputDir>/<RunId>/check__inventory.json``
and exits. Python re-reads via :func:`read_sidecar`. Crashes that produce
no sidecar surface as :class:`ManagerError`.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
import tempfile
from collections.abc import Iterable
from datetime import datetime, timezone
from pathlib import Path
from typing import ClassVar
from uuid import uuid4

from ascendo.interfaces.inventory import IInventory

# ManagerError reused for parity with BrewManager: a dropped IPC contract
# (script crash, missing sidecar, parse failure) is the same conceptual
# error class regardless of whether the failing script is a phase manager
# or an inventory enumerator. Reusing the type avoids forcing callers to
# handle two structurally-identical exceptions.
from ascendo.interfaces.package_manager import ManagerError
from ascendo.models.host import HostInfo, OperatingSystem
from ascendo.models.package import Package, ItemSource, SourceType
from ascendo.models.result import Item, ItemStatus, MessageLevel, Message, Summary
from ascendo.models.run import Phase, PhaseStatus, RunInfo, Trigger
from ascendo.models.sidecar import Sidecar, SidecarSchema, ToolInfo
from ascendo.orchestrator.sidecar_io import (
    SidecarIOError,
    SidecarReadError,
    read_sidecar,
)

_log = logging.getLogger(__name__)


class MacOSInventory(IInventory):
    """Lists installed applications on macOS by shelling out to ``inventory/list.sh``.

    The script invokes ``system_profiler -json -detailLevel mini
    SPApplicationsDataType``, classifies each app by path/name/source into
    one of SYSTEM / MAS / BREW / WEB, and emits an ``ascendo/v1`` sidecar
    at ``<output-dir>/<run-id>/check__inventory.json``.

    Args:
        scripts_dir: Path to ``adapters/macos/scripts/`` (set by the
            adapter; the script we run lives at
            ``<scripts_dir>/inventory/list.sh``).
        lib_dir: Path to ``adapters/macos/lib/`` (informational; the
            script imports the helper files relatively).
        bash_path: Optional override for the bash executable. When
            ``None``, resolves at run time (``/bin/bash`` then ``bash``).
        timeout_sec: Per-call timeout. Default ``300`` (5 min). Inventory
            is read-only and should complete much faster than a phase.
    """

    SCRIPT_REL: ClassVar[str] = "inventory/list.sh"
    DEFAULT_TIMEOUT_SEC: ClassVar[int] = 300

    def __init__(
        self,
        *,
        scripts_dir: Path,
        lib_dir: Path,
        bash_path: str | None = None,
        timeout_sec: int = DEFAULT_TIMEOUT_SEC,
    ) -> None:
        self._scripts_dir: Path = Path(scripts_dir)
        self._lib_dir: Path = Path(lib_dir)
        self._bash_override: str | None = bash_path
        self._bash_resolved: str | None = None
        self._timeout_sec: int = timeout_sec

    # ── Public property for test introspection ───────────────────────

    @property
    def scripts_dir(self) -> Path:
        """Path to the scripts directory (for test introspection)."""
        return self._scripts_dir

    # ── IInventory ───────────────────────────────────────────────────

    def list_installed(
        self,
        host: HostInfo,
        *,
        categories: Iterable[str] | None = None,
    ) -> list[Package]:
        """Spawn ``list.sh``, parse the emitted sidecar, return a list of
        :class:`Package`.

        On non-macOS hosts returns an empty list (no error). This matches
        the IInventory contract: a missing source is not an error condition,
        just zero items.

        Args:
            host: Host context. Non-macOS hosts return ``[]``.
            categories: Optional iterable of :class:`SourceType` values
                (or their string equivalents) used to filter the result.
                When set, only packages whose ``source.type`` matches are
                returned. ``None`` means no filter (default).

        Returns:
            List of :class:`Package`. Order matches the sidecar's
            ``items[]`` order; callers needing stable ordering MUST sort.

        Raises:
            ManagerError: bash unavailable, script crashed without emitting
                a sidecar, sidecar missing on clean exit, or sidecar parse
                failure.
        """
        # Source-availability gate. On a non-macOS host there are simply
        # zero macOS apps to enumerate -> empty list, no error.
        if host.os is not OperatingSystem.MACOS:
            return []

        script_path = self._scripts_dir / self.SCRIPT_REL
        bash = self._resolve_bash()

        # Each list_installed call is its own snapshot — fresh uuid4,
        # private tempdir. This keeps inventory-emitted sidecars from
        # ever colliding with BrewManager phase=check sidecars: even
        # though both write `check__*.json`, they live under
        # different (run-id, base-dir) tuples.
        invocation_run_id = uuid4()

        with tempfile.TemporaryDirectory(prefix="ascendo-inventory-") as tmp_str:
            output_dir = Path(tmp_str)

            argv = self._build_argv(
                bash=bash,
                script_path=script_path,
                run_id=invocation_run_id,
                output_dir=output_dir,
            )

            _log.debug(
                "MacOSInventory.list_installed: run_id=%s argv=%r",
                invocation_run_id,
                argv,
            )

            try:
                completed = subprocess.run(  # noqa: S603 (argv list, not shell)
                    argv,
                    capture_output=True,
                    text=True,
                    timeout=self._timeout_sec,
                    check=False,
                )
            except subprocess.TimeoutExpired as exc:
                msg = (
                    f"inventory list script timed out after "
                    f"{self._timeout_sec}s: {script_path}"
                )
                raise ManagerError(msg) from exc
            except OSError as exc:
                msg = f"failed to spawn bash for inventory list: {exc}"
                raise ManagerError(msg) from exc

            sidecar_path = (
                output_dir
                / str(invocation_run_id)
                / "check__inventory.json"
            )

            if not sidecar_path.exists():
                msg = self._format_missing_sidecar_error(
                    script_path=script_path,
                    sidecar_path=sidecar_path,
                    completed=completed,
                )
                raise ManagerError(msg)

            try:
                sidecar = read_sidecar(sidecar_path)
            except (SidecarReadError, SidecarIOError) as exc:
                msg = (
                    f"inventory list script wrote unparseable sidecar "
                    f"at {sidecar_path}: {exc}"
                )
                raise ManagerError(msg) from exc

            if completed.returncode != 0:
                _log.warning(
                    "inventory list script exited %d but produced a valid "
                    "sidecar; trusting the sidecar (status=%s)",
                    completed.returncode,
                    sidecar.status.value,
                )

            return self._sidecar_to_packages(sidecar, categories=categories)

    def emit_sidecar(
        self,
        run: RunInfo,
        host: HostInfo,
        packages: list[Package],
    ) -> Sidecar:
        """Synthesise an inventory sidecar from a pre-built list of
        :class:`Package`.

        Used when the orchestrator wants to persist an inventory inside a
        bigger run (e.g. as part of a scheduled snapshot) rather than have
        the script run itself. The returned :class:`Sidecar` has
        ``phase=check``, ``category=inventory``, and one ``items[]`` entry
        per package with ``status='up_to_date'`` (the package is installed).

        Args:
            run: The orchestrator's :class:`RunInfo`. Its ``id`` becomes
                the sidecar's run id (in contrast to ``list_installed``,
                which generates a fresh uuid4 per call).
            host: Host context for the ``host`` block of the sidecar.
            packages: Pre-enumerated list of :class:`Package`.

        Returns:
            A validated :class:`Sidecar` (pydantic round-trip enforced).
        """
        now = datetime.now(timezone.utc).isoformat()

        items: list[Item] = []
        for pkg in packages:
            source = pkg.source if pkg.source is not None else ItemSource(
                type=pkg.category, feed=None
            )
            items.append(
                Item(
                    id=pkg.id,
                    name=pkg.name,
                    category=pkg.category,
                    source=source,
                    status=ItemStatus.UP_TO_DATE,
                )
            )

        summary = Summary(
            total=len(items),
            success=0,
            up_to_date=len(items),
            failed=0,
            skipped=0,
            planned=0,
            partial=0,
            duration_ms=None,
            exit_code=0,
        )

        tool = ToolInfo(name="system_profiler", version="1.0", binary_path=None)

        return Sidecar.model_validate(
            {
                "schema": SidecarSchema.V1_ASCENDO,
                "run": run,
                "host": host,
                "tool": tool,
                "phase": Phase.CHECK,
                "category": SourceType.INVENTORY,
                "started_at": now,
                "finished_at": now,
                "status": PhaseStatus.SUCCESS,
                "items": items,
                "summary": summary,
                "messages": [
                    Message(
                        level=MessageLevel.INFO,
                        text=(
                            "Generated by MacOSInventory.emit_sidecar "
                            "(in-memory, not a phase pipeline)."
                        ),
                    ),
                ],
            }
        )

    # ── Internals ────────────────────────────────────────────────────

    def _build_argv(
        self,
        *,
        bash: str,
        script_path: Path,
        run_id: object,
        output_dir: Path,
    ) -> list[str]:
        """Build the bash argv for ``inventory/list.sh``.

        Mirrors :meth:`BrewManager._build_argv` so the same conventions
        apply. Inventory is read-only, so we do NOT emit ``--dry-run``:
        dry-run is meaningless for a non-mutating call.
        """
        return [
            bash,
            str(script_path),
            "--run-id",
            str(run_id),
            "--trigger",
            Trigger.PLUGIN.value,
            "--profile",
            "default",
            "--output-dir",
            str(output_dir),
        ]

    def _sidecar_to_packages(
        self,
        sidecar: Sidecar,
        *,
        categories: Iterable[str] | None,
    ) -> list[Package]:
        """Convert a sidecar's ``items[]`` into :class:`Package` instances.

        Items with synthetic IDs (``__phase_error__`` etc.) are silently
        dropped — they are diagnostic markers, not packages.

        The categories filter (if given) is applied post-hoc using
        ``item.source.type.value``.
        """
        # Normalise the categories filter into a set of SourceType values
        # so we can compare against item.source.type cleanly.
        cat_filter: set[str] | None = None
        if categories is not None:
            cat_filter = set()
            for cat in categories:
                if isinstance(cat, SourceType):
                    cat_filter.add(cat.value)
                else:
                    cat_filter.add(str(cat))

        packages: list[Package] = []
        for item in sidecar.items:
            if item.id.startswith("__") and item.id.endswith("__"):
                # Diagnostic synthetic items emitted by the script's catch
                # block (e.g. __phase_error__).
                continue
            if cat_filter is not None and item.source.type.value not in cat_filter:
                continue
            packages.append(
                Package(
                    id=item.id,
                    name=item.name if item.name else item.id,
                    category=item.source.type,
                    source=item.source,
                )
            )
        return packages

    def _format_missing_sidecar_error(
        self,
        *,
        script_path: Path,
        sidecar_path: Path,
        completed: subprocess.CompletedProcess[str],
    ) -> str:
        """Compose a debugging-friendly error for the missing-sidecar case."""

        def _tail(s: str | None, limit: int = 800) -> str:
            if not s:
                return "<empty>"
            if len(s) <= limit:
                return s
            return f"...<truncated {len(s) - limit} chars>...{s[-limit:]}"

        return (
            f"inventory list script produced no sidecar.\n"
            f"  script:        {script_path}\n"
            f"  expected at:   {sidecar_path}\n"
            f"  exit code:     {completed.returncode}\n"
            f"  stderr (tail): {_tail(completed.stderr)}\n"
            f"  stdout (tail): {_tail(completed.stdout)}"
        )

    def _resolve_bash(self) -> str:
        """Find ``/bin/bash`` (preferred, macOS default) or ``bash`` on PATH.

        Caches result for the lifetime of this instance. Mirrors
        :meth:`BrewManager._resolve_bash` so the two managers stay
        consistent on heterogeneous hosts.
        """
        if self._bash_resolved is not None:
            return self._bash_resolved

        if self._bash_override is not None:
            self._bash_resolved = self._bash_override
            return self._bash_resolved

        # macOS always ships /bin/bash (3.2.x) — check this first.
        if Path("/bin/bash").is_file():
            self._bash_resolved = "/bin/bash"
            return self._bash_resolved

        found = shutil.which("bash")
        if found is not None:
            self._bash_resolved = found
            return found

        msg = (
            "no bash binary found: /bin/bash missing and 'bash' not on PATH. "
            "Pass bash_path= explicitly."
        )
        raise ManagerError(msg)
